<a href="https://colab.research.google.com/github/juandsalazars/pandas-training/blob/main/Numpy_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import the numpy package under the name np
import numpy as np

# Print the numpy version and the configuration
print(np.__version__)

1.26.4


# Array creation

### Create a numpy array of size 10, filled with zeros.

In [3]:
zeros = np.arange(10)*0
zeros

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Create a numpy array with values ranging from 10 to 49

In [4]:
np.arange(10,50)


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Create a numpy matrix of 2*2 integers, filled with ones.

In [5]:
np.ones([2,2], dtype=int)

array([[1, 1],
       [1, 1]])

## Create a numpy matrix of 3*2 float numbers, filled with ones.

In [6]:
np.ones([3,2], dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones.

In [7]:
import random
num = random.randint(5,9)
X = np.arange(num)
X*0 + 1

array([1, 1, 1, 1, 1])

How the repo does it:

In [8]:
np.ones_like(X)

array([1, 1, 1, 1, 1])

## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with zeros.

In [9]:
import random
rows = random.randint(2,9)
cols = random.randint(2,9)
X = np.arange(rows*cols).reshape(rows, cols)
X*0

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

How the repo does it:

In [10]:
np.zeros_like(X)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

## Create a numpy matrix of 4*4 integers, filled with fives.

In [11]:
np.arange(16).reshape(4,4)*0 + 5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

How the repo does it:

In [12]:
np.ones([4,4], dtype=int)*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## Given the X numpy matrix, create a new numpy matrix with the same shape and type as X, filled with sevens.

In [13]:
import random
rows = random.randint(2,9)
cols = random.randint(2,9)
X = np.arange(rows*cols).reshape(rows, cols)
X*0+7

array([[7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7, 7, 7]])

## Create a 3*3 identity numpy matrix with ones on the diagonal and zeros elsewhere.

In [14]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create a numpy array, filled with 3 random integer values between 1 and 10.

In [15]:
np.random.randint(1, 10, size=3)

array([6, 2, 7])

## Create a 3 * 3 * 3 numpy matrix, filled with random float values.

In [16]:
np.random.rand(3,3,3)

array([[[0.77087813, 0.87718167, 0.08705136],
        [0.15799739, 0.07394775, 0.31742492],
        [0.40232751, 0.45666388, 0.45797499]],

       [[0.55219233, 0.16416112, 0.35226173],
        [0.05274106, 0.57056311, 0.36624897],
        [0.80398849, 0.96532173, 0.22419048]],

       [[0.61634902, 0.20809351, 0.78265857],
        [0.67367932, 0.613799  , 0.7268233 ],
        [0.4876789 , 0.32375302, 0.51760755]]])

## Given the X python list convert it to an Y numpy array

In [22]:
X = [1, 20, 300]
print(X, type(X))

Y = np.array(X)
print(Y, type(Y))

[1, 20, 300] <class 'list'>
[  1  20 300] <class 'numpy.ndarray'>


## Given the X numpy array, make a copy and store it on Y.

In [27]:
X = np.arange(10)
Y = X.copy()
X[0] = 1000
print(X)
print(Y)

[1000    1    2    3    4    5    6    7    8    9]
[0 1 2 3 4 5 6 7 8 9]


How the repo does it:

In [31]:
X = np.array([5,2,3])
print(X, id(X))

Y = np.copy(X)
print(Y, id(Y)) # different id

[5 2 3] 134768382839856
[5 2 3] 134768016718704


## Create a numpy array with numbers from 1 to 10

In [36]:
np.arange(10) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

How the repo does it:

In [61]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create a numpy array with the odd numbers between 1 to 10

In [37]:
X = np.arange(10) + 1
X[X % 2 == 1]

array([1, 3, 5, 7, 9])

How the repo does it:

In [38]:
np.arange(1, 11, 2)


array([1, 3, 5, 7, 9])

## Create a numpy array with numbers from 1 to 10, in descending order.

In [51]:
X = (np.arange(10) + 1)
X[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [54]:
np.random.randint(0,8,(3,3), int)

array([[0, 4, 2],
       [5, 6, 3],
       [4, 1, 6]])

How the repo does it:

In [59]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Show the memory size of the given Z numpy matrix

In [65]:
Z = np.zeros((10,10))
Z.size*Z.itemsize

800

How the repo does it:

In [64]:
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


# Array indexation

## Given the X numpy array, show it's first element

In [66]:
X = np.arange(10)
X[0]

0

## Given the X numpy array, show it's last element

In [68]:
X = np.arange(10)
X[-1]

9

## Given the X numpy array, show it's first three elements

In [71]:
X = np.arange(10)
X[0:3]

array([0, 1, 2])

## Given the X numpy array, show all middle elements

In [74]:
X = np.arange(10)
X[1:-1]

array([1, 2, 3, 4, 5, 6, 7, 8])

## Given the X numpy array, show the elements in reverse position

In [75]:
X = np.arange(10)
X[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Given the X numpy array, show the elements in an odd position

In [77]:
X = np.arange(10)
X[::2]

array([0, 2, 4, 6, 8])

## Given the X numpy matrix, show the first row elements

In [86]:
X = np.arange(16).reshape(4,4)
X[0][:]

array([0, 1, 2, 3])

## Given the X numpy matrix, show the last row elements

In [87]:
X = np.arange(16).reshape(4,4)
X[-1]

array([12, 13, 14, 15])

## Given the X numpy matrix, show the first element on first row

In [88]:
X = np.arange(16).reshape(4,4)
X[0][0]

0

How the repo does it:

In [89]:
X[0,0]

0

## Given the X numpy matrix, show the last element on last row

In [91]:
X = np.arange(16).reshape(4,4)
X[-1][-1]

15

## Given the X numpy matrix, show the middle row elements

In [92]:
X = np.arange(16).reshape(4,4)
X[1:-1]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

How the repo does it:

In [93]:
#X[1:-1][1:-1] wrong!
X[1:-1, 1:-1]

array([[ 5,  6],
       [ 9, 10]])

## Given the X numpy matrix, show the first two elements on the first two rows

In [96]:
X = np.arange(16).reshape(4,4)
X[:2,:2]

array([[0, 1],
       [4, 5]])

## Given the X numpy matrix, show the last two elements on the last two rows

In [100]:
X = np.arange(25).reshape(5,5)
X[-2:,-2:]

array([[18, 19],
       [23, 24]])

# Array manipulation

## Convert the given integer numpy array to float

In [103]:
X = np.array([1,2,3,4,5])
np.array(X, float)

array([1., 2., 3., 4., 5.])

## Reverse the given numpy array (first element becomes last)

In [105]:
X = np.arange(10)
X[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## Order (sort) the given numpy array

In [109]:
X = np.random.randint(10, size=10)
X.sort()
print(X)

[2 4 4 5 7 7 8 8 8 9]


## Given the X numpy array, set the fifth element equal to 1

In [111]:
X = np.arange(10)
X[4] = 1
X

array([0, 1, 2, 3, 1, 5, 6, 7, 8, 9])

## Given the X numpy array, change the 50 with a 40

In [114]:
X = np.arange(0, 51, 10)
X[-1] = 40
X

array([ 0, 10, 20, 30, 40, 40])

## Given the X numpy matrix, change the last row with all 1

In [120]:
X = np.arange(16).reshape(4,4)
X[-1] = 1
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  1,  1,  1]])

How the repo does it:

In [121]:
X[-1] = np.array([1, 1, 1, 1])
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 1,  1,  1,  1]])

## Given the X numpy matrix, change the last item on the last row with a 0

In [124]:
X = np.arange(16).reshape(4,4)
X[-1, -1] = 0
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14,  0]])

## Given the X numpy matrix, add 5 to every element

In [125]:
X = np.arange(16).reshape(4,4)
X + 5

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

# Boolean arrays (also called masks)

## Given the X numpy array, make a mask showing negative elements

In [128]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X < 0

array([ True, False, False,  True, False, False, False, False,  True,
       False])

How the repo does it (which I think is wrong because 0 is not negative):

In [130]:
mask = X <= 0
mask

array([ True, False,  True,  True, False, False,  True,  True,  True,
       False])

## Given the X numpy array, get the negative elements

In [132]:
X = np.array([-1,2,0,-4,5,6,0,0,-9,10])
X[X < 0]

array([-1, -4, -9])

## Given the X numpy array, get numbers higher than 5

In [134]:
X[X>5]

array([ 6, 10])

## Given the X numpy array, get numbers higher than the elements mean

In [136]:
X[X > X.mean()]

array([ 2,  5,  6, 10])

## Given the X numpy array, get numbers equal to 2 or 10

In [143]:
X[(X == 2) | (X == 10)]

array([ 2, 10])

# Logic functions

## Given the X numpy array, return True if none of its elements is zero

In [148]:
X = np.array([-1, 2, 0, -4, 5, 6, 0, 0, -9, 10])
X.all()

False

## Given the X numpy array, return True if any of its elements is zero

In [150]:
X.any()

True

# Summary statistics

## Given the X numpy array, show the sum of its elements

In [152]:
X = np.array([3, 5, 6, 7, 2, 3, 4, 9, 4])
X.sum()

43

## Given the X numpy array, show the mean value of its elements


In [154]:
X.mean()

4.777777777777778

## Given the X numpy matrix, show the sum of its columns

In [160]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.sum(axis=0)

array([24, 28, 32, 36])

## Given the X numpy matrix, show the mean value of its rows

In [162]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.mean(axis=1)

array([ 2.5,  6.5, 10.5, 14.5])

## Given the X numpy array, show the max value of its elements

In [163]:
X = np.array([
    [1,   2,  3,  4],
    [5,   6,  7,  8],
    [9,  10, 11, 12],
    [13, 14, 15, 16]
])
X.max()

16